/**
 * @reverie/core — shared types and the prototype's tested domain logic, ported (not
 * rewritten) as pure functions: the merge engine, the Goodreads/StoryGraph CSV importer,
 * and cover-URL helpers.
 */

/** The product name. Kept in one place so a rename touches a single line. */
export const APP_NAME = 'Reverie'

export * from './types'
export * from './partialDate'
export * from './readingHistory'
export * from './readingPlan'
export * from './sourcePace'
export * from './httpClassify'
export * from './normalize'
export * from './id'
export * from './covers'
export * from './coverQuality'
export * from './personalCoverStudio'
export * from './merge'
export * from './csv'
export * from './libraryCsv'
export * from './seriesTitle'
export * from './isbnNotice'
export * from './providerComparison'
export * from './filters'
export * from './discoverCurated'
export * from './ownership'
export * from './statePill'
export * from './coverOverlay'
export * from './shelves'
export * from './match'
export * from './mergeBookPicker'
export * from './buyLinks'
export * from './labels'
export * from './skinVoice'
export * from './skinStructure'
export * from './spine'
export * from './spineTint'
export * from './matcher'
export * from './nextRead'
export * from './embedding'
export * from './tags'
export * from './tasteProfile'
export * from './tasteEval'
export * from './skins'
export * from './tasteTier'
export * from './adaptive'
export * from './enrich'
export * from './enrichResolve'
export * from './enrichReview'
export * from './coverPlaceholder'
export * from './brokenCovers'
export * from './contributors'
export * from './indie'
export * from './observability'
export * from './genreNormalize'
export * from './seriesStatus'
export * from './seriesClaim'
export * from './seriesClassification'
export * from './proEntitlement'
export * from './seriesShelf'
export * from './seriesIndex'
export * from './seriesConsolidation'
export * from './numericField'
export * from './coverGradient'
export * from './tropes'
export * from './moods'
export * from './importMap'
export * from './supabaseError'
export * from './titleCase'
export { latestRatingByFormat, type FormatRating } from './formatRatings'
export { snapHalfRating } from './rating'
export * from './mergeFieldPicker'
export * from './discovery'
